<div class="alert alert-block alert-custom" style="margin-top: 20px; background-color: #f0f8ff; color:#f0f8ff; border-color: #5a6268;">
  

<h1 align="center"><font size="6" face="Tahoma"><span style="color:black">Check out my GitHub</span>
</font></h1>

<p style="text-align:center">
    <a href="https://github.com/Prasun157" target="_blank">
    <img src="https://mattloftus.github.io/images/github-icon.svg" width="150" alt="Logo">
    </a>
</p</div>
    

<p style="text-align:center">
    
<img src="https://storage.googleapis.com/kaggle-datasets-images/3233223/5623667/be5c1ab69522cfed31611c4f000c5b1b/dataset-cover.jpeg?t=2023-05-07-06-58-52" width="700" alt="Logo">
    </a>
</p>

# Introduction: Data Preprocessing for BRFSS 2021 Diabetes Prediction
---

This notebook details the data preprocessing steps for the __Behavioral Risk Factor Surveillance System__ (BRFSS) 2021 dataset, aimed at preparing it for machine learning models to predict diabetes. The focus is on generating a balanced binary dataset appropriate for machine learning algorithms.

### Extracted Features

The following features will be extracted from the original dataset:

- **DIABETE4**: Awareness of diabetes
- **CHILDREN**: Number of they have
- **_RFHYPE6**: Awareness of high blood pressure ("yes
- **EMPLOY1**: Employee level" or "no")
- **TOLDHI3**: Awareness of cholesterol levels ("yes" or "no")
- **_CHOLCH3**: Cholesterol check within the past five years ("yes" or "no")
- **_BMI5**: Body mass index (scale)
- **SMOKE100**: Smoked at least 100 cigarettes ("yes" or "no")
- **CVDSTRK3**: Presence of chronic health conditions ("yes" or "no")
- **_MICHD**: History of coronary heart disease or myocardial infarction ("yes" or "no")
- **_TOTINDA**: Engagement in leisure-time physical activity
- **_FRTLT1A**: Consumes fruit one or more times per day ("yes" or "no")
- **_VEGLT1A**: Consumes vegetables one or more times per day ("yes" or "no")
- **_RFDRHV7**: Heavy alcohol consumption ("yes" or "no")
- **_HLTHPLN**: Possession of health insurance ("yes" or "no")
- **MEDCOST1**: Inability to afford seeing a doctor ("yes" or "no")
- **GENHLTH**: General health status ("excellent", "very good", "good", "fair", "poor")
- **MENTHLTH**: Number of days mental health was not good (scale based on the number of days)
- **PHYSHLTH**: Number of days physical health was not good (scale based on the number of days)
- **DIFFWALK**: Difficulty walking or climbing stairs ("yes" or "no")
- **_SEX**: Gender ("male" or "female")
- **_AGEG5YR**: Age group (in 5-year intervals)
- **EDUCA**: Highest level of education attained
- **INCOME3**: gories) income (11 categories)

<div class="alert alert-block alert-custom" style="margin-top: 20px; background-color:#f0f8ff; color:#1560bd; border-color: #5a6268;">
<h3>Obectives</h3>   
    
1. [Importing data](#0)<br>
2. [Handle missing values](#2)<br>
3. [Correct data format](#4)<br>
4. [Column Renaming](#6)<br>
5. [Save the cleaned dataset to a csv file and SQL server](#20)<br>
6. [Change log](#20)<br>



</div>



# Data Wrangling
---

## Libarary Importing
---

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
import warnings
# Suppress all warnings
warnings.filterwarnings('ignore')

## Data importing and briefing
---

In [7]:
#importing data
df_original_brfss=pd.read_csv("LLCP2021.CSV")
df_original_brfss

_STATE  FMONTH     IDATE  IMONTH  IDAY  IYEAR  DISPCODE       SEQNO  \
0            1       1   1192021       1    19   2021      1100  2021000001   
1            1       1   1212021       1    21   2021      1100  2021000002   
2            1       1   1212021       1    21   2021      1100  2021000003   
3            1       1   1172021       1    17   2021      1100  2021000004   
4            1       1   1152021       1    15   2021      1100  2021000005   
...        ...     ...       ...     ...   ...    ...       ...         ...   
438688      78      12   1062022       1     6   2022      1100  2021001381   
438689      78      12   1122022       1    12   2022      1100  2021001382   
438690      78      12  12212021      12    21   2021      1100  2021001383   
438691      78      12   1112022       1    11   2022      1100  2021001384   
438692      78      12  12222021      12    22   2021      1100  2021001385   

              _PSU  CTELENM1  ...  _FRTRES1  _VEGRES1  _FRUTSU1  _VEGESU1  \
0       2021000001       1.0  ...         1         1     100.0     214.0   
1       2021000002       1.0  ...         1         1     100.0     128.0   
2       2021000003       1.0  ...         1         1     100.0      71.0   
3       2021000004       1.0  ...         1         1     114.0     165.0   
4       2021000005       1.0  ...         1         1     100.0     258.0   
...            ...       ...  ...       ...       ...       ...       ...   
438688  2021001381       NaN  ...         1         1     157.0     393.0   
438689  2021001382       NaN  ...         1         1     200.0     157.0   
438690  2021001383       NaN  ...         1         1     200.0     143.0   
438691  2021001384       NaN  ...         1         1     100.0     156.0   
438692  2021001385       NaN  ...         1         1      34.0      66.0   

        _FRTLT1A  _VEGLT1A  _FRT16A  _VEG23A  _FRUITE1  _VEGETE1  
0              1         1        1        1         0         0  
1              1         1        1        1         0         0  
2              1         2        1        1         0         0  
3              1         1        1        1         0         0  
4              1         1        1        1         0         0  
...          ...       ...      ...      ...       ...       ...  
438688         1         1        1        1         0         0  
438689         1         1        1        1         0         0  
438690         1         1        1        1         0         0  
438691         1         1        1        1         0         0  
438692         2         2        1        1         0         0  

[438693 rows x 303 columns]

In [8]:
#dimensions of the given dataset
print(f"dimensions of the given dataset: {df_original_brfss.shape }")

dimensions of the given dataset: (438693, 303)


In [9]:
#Check that the data loaded in is in the correct format
pd.set_option('display.max_columns', 500)
df_original_brfss.head()


_STATE  FMONTH    IDATE  IMONTH  IDAY  IYEAR  DISPCODE       SEQNO  \
0       1       1  1192021       1    19   2021      1100  2021000001   
1       1       1  1212021       1    21   2021      1100  2021000002   
2       1       1  1212021       1    21   2021      1100  2021000003   
3       1       1  1172021       1    17   2021      1100  2021000004   
4       1       1  1152021       1    15   2021      1100  2021000005   

         _PSU  CTELENM1  PVTRESD1  COLGHOUS  STATERE1  CELPHON1  LADULT1  \
0  2021000001       1.0       1.0       NaN       1.0       2.0      1.0   
1  2021000002       1.0       1.0       NaN       1.0       2.0      1.0   
2  2021000003       1.0       1.0       NaN       1.0       2.0      1.0   
3  2021000004       1.0       1.0       NaN       1.0       2.0      1.0   
4  2021000005       1.0       1.0       NaN       1.0       2.0      1.0   

   COLGSEX  NUMADULT  LANDSEX  NUMMEN  NUMWOMEN  RESPSLCT  SAFETIME  CTELNUM1  \
0      NaN       2.0      NaN     1.0       1.0       2.0       NaN       NaN   
1      NaN       2.0      NaN     1.0       1.0       2.0       NaN       NaN   
2      NaN       2.0      NaN     1.0       1.0       2.0       NaN       NaN   
3      NaN       2.0      NaN     1.0       1.0       2.0       NaN       NaN   
4      NaN       2.0      NaN     1.0       1.0       1.0       NaN       NaN   

   CELLFON5  CADULT1  CELLSEX  PVTRESD3  CCLGHOUS  CSTATE1  LANDLINE  HHADULT  \
0       NaN      NaN      NaN       NaN       NaN      NaN       NaN      NaN   
1       NaN      NaN      NaN       NaN       NaN      NaN       NaN      NaN   
2       NaN      NaN      NaN       NaN       NaN      NaN       NaN      NaN   
3       NaN      NaN      NaN       NaN       NaN      NaN       NaN      NaN   
4       NaN      NaN      NaN       NaN       NaN      NaN       NaN      NaN   

   SEXVAR  GENHLTH  PHYSHLTH  MENTHLTH  POORHLTH  PRIMINSR  PERSDOC3  \
0       2      5.0      20.0      10.0      88.0       3.0       1.0   
1       2      3.0      88.0      88.0       NaN       1.0       2.0   
2       2      2.0      88.0      88.0       NaN       2.0       2.0   
3       2      2.0      88.0      10.0      88.0       2.0       1.0   
4       1      5.0      30.0      88.0      30.0       3.0       1.0   

   MEDCOST1  CHECKUP1  EXERANY2  BPHIGH6  BPMEDS  CHOLCHK3  TOLDHI3  CHOLMED3  \
0       2.0       2.0       2.0      3.0     NaN       2.0      1.0       1.0   
1       2.0       1.0       1.0      1.0     1.0       2.0      1.0       1.0   
2       2.0       1.0       2.0      1.0     1.0       2.0      2.0       2.0   
3       2.0       1.0       1.0      1.0     1.0       2.0      1.0       2.0   
4       2.0       1.0       1.0      4.0     NaN       2.0      1.0       1.0   

   CVDINFR4  CVDCRHD4  CVDSTRK3  ASTHMA3  ASTHNOW  CHCSCNCR  CHCOCNCR  \
0       2.0       2.0       2.0      1.0      1.0       2.0       2.0   
1       2.0       1.0       2.0      2.0      NaN       2.0       2.0   
2       2.0       1.0       2.0      2.0      NaN       2.0       2.0   
3       2.0       2.0       2.0      2.0      NaN       2.0       2.0   
4       1.0       7.0       1.0      2.0      NaN       2.0       2.0   

   CHCCOPD3  ADDEPEV3  CHCKDNY2  DIABETE4  DIABAGE3  HAVARTH5  ARTHEXER  \
0       1.0       2.0       2.0       3.0       NaN       1.0       2.0   
1       2.0       2.0       1.0       1.0      98.0       1.0       1.0   
2       2.0       2.0       2.0       1.0      98.0       2.0       NaN   
3       2.0       2.0       2.0       1.0      56.0       2.0       NaN   
4       2.0       2.0       2.0       1.0      65.0       2.0       NaN   

   ARTHEDU  LMTJOIN3  ARTHDIS2  JOINPAI2  MARITAL  EDUCA  RENTHOM1  NUMHHOL3  \
0      2.0       2.0       1.0       8.0      1.0    4.0       1.0       1.0   
1      2.0       1.0       1.0      10.0      9.0    6.0       1.0       2.0   
2      NaN       NaN       NaN       NaN      3.0    4.0       1.0       2.0   
3  

In [10]:
df_original_brfss.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438693 entries, 0 to 438692
Columns: 303 entries, _STATE to _VEGETE1
dtypes: float64(245), int64(58)
memory usage: 1014.1 MB




## Deal with missing data 
---

<b>How should you deal with missing data?</b>

<ol>
    <li>Drop data<br>
        a. Drop the whole row<br>
        b. Drop the whole column
    </li>
    <li>Replace data<br>
        a. Replace it by mean<br>
        b. Replace it by frequency<br>
        c. Replace it based on other functions
    </li>
</ol>

</div>


In [11]:
#selecting necessary features
df = df_original_brfss[['DIABETE4','CHILDREN','EMPLOY1', '_RFHYPE6', 'TOLDHI3', '_CHOLCH3', '_BMI5', 'SMOKE100', 'CVDSTRK3', '_MICHD', '_TOTINDA', '_FRTLT1A', '_VEGLT1A', '_RFDRHV7', '_HLTHPLN', 'MEDCOST1', 'GENHLTH', 'MENTHLTH', 'PHYSHLTH', 'DIFFWALK', '_SEX', '_AGEG5YR', 'EDUCA', 'INCOME3' ]]

In [12]:
df.head()

DIABETE4  CHILDREN  EMPLOY1  _RFHYPE6  TOLDHI3  _CHOLCH3   _BMI5  SMOKE100  \
0       3.0      88.0      7.0         1      1.0         1  1454.0       1.0   
1       1.0      88.0      8.0         2      1.0         1     NaN       2.0   
2       1.0      88.0      7.0         2      2.0         1  2829.0       2.0   
3       1.0      88.0      7.0         2      1.0         1  3347.0       2.0   
4       1.0      88.0      8.0         1      1.0         1  2873.0       2.0   

   CVDSTRK3  _MICHD  _TOTINDA  _FRTLT1A  _VEGLT1A  _RFDRHV7  _HLTHPLN  \
0       2.0     2.0         2         1         1         1         1   
1       2.0     1.0         1         1         1         1         1   
2       2.0     1.0         2         1         2         1         1   
3       2.0     2.0         1         1         1         1         1   
4       1.0     1.0         1         1         1         1         1   

   MEDCOST1  GENHLTH  MENTHLTH  PHYSHLTH  DIFFWALK  _SEX  _AGEG5YR  EDUCA  \
0       2.0      5.0      10.0      20.0       2.0     2        11    4.0   
1       2.0      3.0      88.0      88.0       1.0     2        10    6.0   
2       2.0      2.0      88.0      88.0       2.0     2        11    4.0   
3       2.0      2.0      10.0      88.0       2.0     2         9    4.0   
4       2.0      5.0      88.0      30.0       1.0     1        12    3.0   

   INCOME3  
0      5.0  
1     77.0  
2      3.0  
3      7.0  
4      4.0

In [13]:
#checking for missing values
df.isnull().sum()


DIABETE4        3
CHILDREN     6135
EMPLOY1      3588
_RFHYPE6        0
TOLDHI3     60836
_CHOLCH3        0
_BMI5       46852
SMOKE100    21232
CVDSTRK3        2
_MICHD       4635
_TOTINDA        0
_FRTLT1A        0
_VEGLT1A        0
_RFDRHV7        0
_HLTHPLN        0
MEDCOST1        5
GENHLTH         4
MENTHLTH        2
PHYSHLTH        3
DIFFWALK    18009
_SEX            0
_AGEG5YR        0
EDUCA           5
INCOME3      8847
dtype: int64

In [14]:
#CHILDREN: number of  children 
#Replacing the null values in Children column with the most frequent occuring value

most_freq_child=df['CHILDREN'].astype('object').value_counts().idxmax()
df['CHILDREN'].replace(np.NaN , most_freq_child , inplace=True)
print(f"NUll Values in Childrens column = {df['CHILDREN'].isnull().sum()}")


# going to make this ordinal. 88 is for no children changing that to 0
# Remove all 99 (dont knows)
# channging all value greater then 10 to 10
#df = df[df.CHILDREN != 99]
df['CHILDREN'] = df['CHILDREN'].replace({88:0 , 99:0})
df['CHILDREN'][df['CHILDREN']>10]=10
df.CHILDREN.unique()


NUll Values in Childrens column = 0


array([ 0.,  1.,  2.,  3.,  5.,  7.,  4.,  6., 10.,  8.,  9.])

In [15]:
#EMPLOY1 is already set column
most_freq_=df['EMPLOY1'].astype('object').value_counts().idxmax()
df['EMPLOY1'].replace(np.NaN , most_freq_ , inplace=True)
print(f"NUll Values in Childrens column = {df['EMPLOY1'].isnull().sum()}")

NUll Values in Childrens column = 0


In [16]:
#Drop Missing Values
df = df.dropna()
df.shape

(330355, 24)

In [17]:
# DIABETE4 = Diabetes Awareness
# going to make this ordinal. 0 is for no diabetes or only during pregnancy, 1 is for pre-diabetes or borderline diabetes, 2 is for yes diabetes
# Remove all 7 (dont knows)
# Remove all 9 (refused)
df['DIABETE4'] = df['DIABETE4'].replace({2:0, 3:0, 1:2, 4:1})
df = df[df.DIABETE4 != 7]
df = df[df.DIABETE4 != 9]
df.DIABETE4.unique()

array([0., 2., 1.])

In [18]:
#1 _RFHYPE6 = High Blood Pressure Awareness
#Change 1 to 0 so it represetnts No high blood pressure and 2 to 1 so it represents high blood pressure

df['_RFHYPE6'] = df['_RFHYPE6'].replace({1:0, 2:1})
df = df[df._RFHYPE6 != 9]
df._RFHYPE6.unique()

array([0, 1], dtype=int64)

In [19]:

# TOLDHI3 = Cholesterol Awareness
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)

df['TOLDHI3'] = df['TOLDHI3'].replace({2:0})
df = df[df.TOLDHI3 != 7]
df = df[df.TOLDHI3 != 9]
df.TOLDHI3.unique()


array([1., 0.])

In [20]:
# # Remove all 7 (dont knows)
# # Remove all 9 (refused)

# # Remove all 77 (dont knows)
# # Remove all 99 (refused)

# df = df[df != 7]
# df = df[df != 9]
# df = df[df.PHYSHLTH != 77]
# df = df[df.PHYSHLTH != 99]
# df = df[df.MENTHLTH != 77]
# df = df[df.MENTHLTH != 99]

# # _AGEG5YR = Reported age in five-year age categories
# # 5 year increments. It is already ordinal. 1 is 18-24 all the way up to 13 which is 80 and older
# # Remove all 14 (don't know or missing)

# df = df[df._AGEG5YR != 14]

In [21]:
# _CHOLCH3 = Cholesterol check within past five years
# Change 3 to 0 and 2 to 0 for Not checked cholesterol in past 5 years
# Remove 9 (don't know/refused)
df['_CHOLCH3'] = df['_CHOLCH3'].replace({3:0,2:0})
df = df[df._CHOLCH3 != 9]
df._CHOLCH3.unique()

array([1, 0], dtype=int64)

In [22]:
# _BMI5 = Body mass index
# BMI are * 100
df['_BMI5'] = df['_BMI5'].div(100).round(0)
df._BMI5.unique()

array([15., 28., 33., 29., 24., 46., 23., 40., 27., 35., 18., 30., 25.,
       36., 22., 31., 45., 26., 14., 38., 21., 32., 20., 19., 34., 41.,
       43., 44., 39., 37., 16., 42., 50., 51., 17., 52., 47., 49., 56.,
       57., 48., 58., 61., 53., 63., 64., 54., 68., 55., 62., 13., 59.,
       89., 66., 77., 60., 87., 69., 72., 75., 67., 71., 65., 82., 86.,
       70., 78., 12., 74., 98., 73., 84., 76., 80., 83., 79., 99., 88.,
       81., 90., 92., 91., 95., 85., 94.])

In [23]:
# SMOKE100 = Smoked at Least 100 Cigarettes
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)

df['SMOKE100'] = df['SMOKE100'].replace({2:0})
df = df[df.SMOKE100 != 7]
df = df[df.SMOKE100 != 9]
df.SMOKE100.unique()

array([1., 0.])

In [24]:
df['CVDSTRK3'] = df['CVDSTRK3'].replace({2:0})
df = df[df.CVDSTRK3 != 7]
df = df[df.CVDSTRK3 != 9]
print(df.CVDSTRK3.unique())

df['_MICHD'] = df['_MICHD'].replace({2: 0})

df['_TOTINDA'] = df['_TOTINDA'].replace({2:0})
df = df[df._TOTINDA != 9]
print(df._TOTINDA.unique())

df['_FRTLT1A'] = df['_FRTLT1A'].replace({2:0})
df = df[df._FRTLT1A != 9]
print(df._FRTLT1A.unique())

df['_VEGLT1A'] = df['_VEGLT1A'].replace({2:0})
df = df[df._VEGLT1A != 9]
print(df._VEGLT1A.unique())

df['_RFDRHV7'] = df['_RFDRHV7'].replace({1:0, 2:1})
df = df[df._RFDRHV7 != 9]
print(df._RFDRHV7.unique())

df['_HLTHPLN'] = df['_HLTHPLN'].replace({2:0})
df = df[df._HLTHPLN != 7]
df = df[df._HLTHPLN != 9]
print(df._HLTHPLN.unique())

df['MEDCOST1'] = df['MEDCOST1'].replace({2:0})
df = df[df.MEDCOST1 != 7]
df = df[df.MEDCOST1 != 9]
print(df.MEDCOST1.unique())

df = df[df.GENHLTH != 7]
df = df[df.GENHLTH != 9]
print(df.GENHLTH.unique())

df['MENTHLTH'] = df['MENTHLTH'].replace({88:0})
df = df[df.MENTHLTH != 77]
df = df[df.MENTHLTH != 99]
print(df.MENTHLTH.unique())

df['PHYSHLTH'] = df['PHYSHLTH'].replace({88:0})
df = df[df.PHYSHLTH != 77]
df = df[df.PHYSHLTH != 99]
print(df.PHYSHLTH.unique())

df['DIFFWALK'] = df['DIFFWALK'].replace({2:0})
df = df[df.DIFFWALK != 7]
df = df[df.DIFFWALK != 9]
print(df.DIFFWALK.unique())

df['_SEX'] = df['_SEX'].replace({2:0})
print(df._SEX.unique())

df = df[df._AGEG5YR != 14]
print(df._AGEG5YR.unique())

df = df[df.EDUCA != 9]
print(df.EDUCA.unique())


[0. 1.]
[0 1]
[1 0]
[1 0]
[0 1]
[1 0]
[0. 1.]
[5. 2. 3. 4. 1.]
[10.  0.  5. 25.  2.  7. 30.  3. 14. 20.  8.  1. 15.  4. 28. 24. 21. 12.
  6. 22. 27. 18. 13. 17. 16.  9. 19. 29. 23. 11. 26.]
[20.  0. 30. 25.  1.  4. 10.  2.  3. 15.  8. 13. 14.  5.  7.  6. 24. 29.
 18.  9. 16. 17. 26. 28. 12. 21. 27. 11. 19. 22. 23.]
[0. 1.]
[0 1]
[11  9 12 13 10  7  6  8  4  3  5  2  1]
[4. 3. 5. 6. 2. 1.]


In [25]:
# INCOME3 = Income Level
# This is already an ordinal variable with 1 being less than $10,000 all the way up to 11 being $200,000 or more
# Remove all 77 (dont knows)
# Remove all 99 (refused)
df = df[df.INCOME3 != 77]
df = df[df.INCOME3 != 99]
df.INCOME3.unique()

array([ 5.,  3.,  7.,  4.,  6.,  8.,  2.,  9., 10.,  1., 11.])

In [26]:
df.shape

(236378, 24)

In [27]:
df.head(5)


DIABETE4  CHILDREN  EMPLOY1  _RFHYPE6  TOLDHI3  _CHOLCH3  _BMI5  SMOKE100  \
0       0.0       0.0      7.0         0      1.0         1   15.0       1.0   
2       2.0       0.0      7.0         1      0.0         1   28.0       0.0   
3       2.0       0.0      7.0         1      1.0         1   33.0       0.0   
4       2.0       0.0      8.0         0      1.0         1   29.0       0.0   
5       0.0       0.0      7.0         0      0.0         1   24.0       1.0   

   CVDSTRK3  _MICHD  _TOTINDA  _FRTLT1A  _VEGLT1A  _RFDRHV7  _HLTHPLN  \
0       0.0     0.0         0         1         1         0         1   
2       0.0     1.0         0         1         0         0         1   
3       0.0     0.0         1         1         1         0         1   
4       1.0     1.0         1         1         1         0         1   
5       0.0     0.0         0         0         0         0         1   

   MEDCOST1  GENHLTH  MENTHLTH  PHYSHLTH  DIFFWALK  _SEX  _AGEG5YR  EDUCA  \
0       0.0      5.0      10.0      20.0       0.0     0        11    4.0   
2       0.0      2.0       0.0       0.0       0.0     0        11    4.0   
3       0.0      2.0      10.0       0.0       0.0     0         9    4.0   
4       0.0      5.0       0.0      30.0       1.0     1        12    3.0   
5       0.0      3.0       0.0       0.0       1.0     1        13    5.0   

   INCOME3  
0      5.0  
2      3.0  
3      7.0  
4      4.0  
5      6.0

In [28]:
#Check Class Sizes of the heart disease column
df.groupby(['DIABETE4']).size()

DIABETE4
0.0    197191
1.0      5619
2.0     33568
dtype: int64


## Data Type Conversion 
--- 


In [29]:
#checking data types of all features
df.dtypes


DIABETE4    float64
CHILDREN    float64
EMPLOY1     float64
_RFHYPE6      int64
TOLDHI3     float64
_CHOLCH3      int64
_BMI5       float64
SMOKE100    float64
CVDSTRK3    float64
_MICHD      float64
_TOTINDA      int64
_FRTLT1A      int64
_VEGLT1A      int64
_RFDRHV7      int64
_HLTHPLN      int64
MEDCOST1    float64
GENHLTH     float64
MENTHLTH    float64
PHYSHLTH    float64
DIFFWALK    float64
_SEX          int64
_AGEG5YR      int64
EDUCA       float64
INCOME3     float64
dtype: object

In [30]:
#converting them to Intereger form
df=df.astype('int')

In [32]:
df.head()

DIABETE4  CHILDREN  EMPLOY1  _RFHYPE6  TOLDHI3  _CHOLCH3  _BMI5  SMOKE100  \
0         0         0        7         0        1         1     15         1   
2         2         0        7         1        0         1     28         0   
3         2         0        7         1        1         1     33         0   
4         2         0        8         0        1         1     29         0   
5         0         0        7         0        0         1     24         1   

   CVDSTRK3  _MICHD  _TOTINDA  _FRTLT1A  _VEGLT1A  _RFDRHV7  _HLTHPLN  \
0         0       0         0         1         1         0         1   
2         0       1         0         1         0         0         1   
3         0       0         1         1         1         0         1   
4         1       1         1         1         1         0         1   
5         0       0         0         0         0         0         1   

   MEDCOST1  GENHLTH  MENTHLTH  PHYSHLTH  DIFFWALK  _SEX  _AGEG5YR  EDUCA  \
0         0        5        10        20         0     0        11      4   
2         0        2         0         0         0     0        11      4   
3         0        2        10         0         0     0         9      4   
4         0        5         0        30         1     1        12      3   
5         0        3         0         0         1     1        13      5   

   INCOME3  
0        5  
2        3  
3        7  
4        4  
5        6

## Column Renaming
--- 


In [35]:
#Rename the columns to make them more readable
df_final = df.rename(columns = {'DIABETE4':'Diabetes','CHILDREN':'children' , 'EMPLOY1':'employ' ,'_RFHYPE6':'HighBP', 'TOLDHI3':'HighChol', '_CHOLCH3':'CholCheck', '_BMI5':'BMI', 'SMOKE100':'Smoker',
                                            'CVDSTRK3':'Stroke','_MICHD':'HeartDiseaseorAttack', '_TOTINDA':'PhysActivity', '_FRTLT1A':'Fruits', '_VEGLT1A':"Veggies",
                                            '_RFDRHV7':'HvyAlcoholConsump',    '_HLTHPLN':'AnyHealthcare',   'MEDCOST1':'NoDocbcCost', 'GENHLTH':'GenHlth',
                                            'MENTHLTH':'MentHlth', 'PHYSHLTH':'PhysHlth',   'DIFFWALK':'DiffWalk', '_SEX':'Sex', '_AGEG5YR':'Age',
                                            'EDUCA':'Education', 'INCOME3':'Income' })


In [36]:
df_final.head()

Diabetes  children  employ  HighBP  HighChol  CholCheck  BMI  Smoker  \
0         0         0       7       0         1          1   15       1   
2         2         0       7       1         0          1   28       0   
3         2         0       7       1         1          1   33       0   
4         2         0       8       0         1          1   29       0   
5         0         0       7       0         0          1   24       1   

   Stroke  HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  \
0       0                     0             0       1        1   
2       0                     1             0       1        0   
3       0                     0             1       1        1   
4       1                     1             1       1        1   
5       0                     0             0       0        0   

   HvyAlcoholConsump  AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  \
0                  0              1            0        5        10        20   
2                  0              1            0        2         0         0   
3                  0              1            0        2        10         0   
4                  0              1            0        5         0        30   
5                  0              1            0        3         0         0   

   DiffWalk  Sex  Age  Education  Income  
0         0    0   11          4       5  
2         0    0   11          4       3  
3         0    0    9          4       7  
4         1    1   12          3       4  
5         1    1   13          5       6

## Save the cleaned dataset to a csv file and SQL server
---

In [37]:
df_final.to_csv('diabetes_health_indicators_cleaned.csv', sep=",", index=False)

In [42]:
#Establishing connection the sql server
conn = 'mysql+mysqlconnector://root:****@localhost:3306/Krankenhaus'

In [41]:

from sqlalchemy import create_engine


# Create a SQLAlchemy engine
engine = create_engine(f'mysql+mysqlconnector://root:****@localhost:3306/Krankenhaus')


# Write the DataFrame to a MySQL table named 'diabets_data' in Krankenhaus database
df_final.to_sql('diabetes_data', con=engine, if_exists='replace', index=False)




236378

In [40]:
# Read the table back into a Database to verify
df_from_sql = pd.read_sql('diabetes_data', con=engine)

df_from_sql

Diabetes  children  employ  HighBP  HighChol  CholCheck  BMI  Smoker  \
0              0         0       7       0         1          1   15       1   
1              2         0       7       1         0          1   28       0   
2              2         0       7       1         1          1   33       0   
3              2         0       8       0         1          1   29       0   
4              0         0       7       0         0          1   24       1   
...          ...       ...     ...     ...       ...        ...  ...     ...   
236373         2         0       7       1         1          1   21       0   
236374         0         1       1       1         0          1   25       1   
236375         0         0       7       0         1          1   31       0   
236376         0         0       7       1         0          1   24       0   
236377         0         0       1       0         1          1   32       0   

        Stroke  HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  \
0            0                     0             0       1        1   
1            0                     1             0       1        0   
2            0                     0             1       1        1   
3            1                     1             1       1        1   
4            0                     0             0       0        0   
...        ...                   ...           ...     ...      ...   
236373       0                     0             1       1        1   
236374       0                     0             1       1        1   
236375       0                     0             1       1        1   
236376       0                     0             1       1        1   
236377       0                     0             1       0        0   

        HvyAlcoholConsump  AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  \
0                       0              1            0        5        10   
1                       0              1            0        2         0   
2                       0              1            0        2        10   
3                       0              1            0        5         0   
4                       0              1            0        3         0   
...                   ...            ...          ...      ...       ...   
236373                  0              1            0        4         0   
236374                  0              0            1        2        20   
236375                  0              1            0        2         0   
236376                  0              1            0        2         0   
236377                  0              1            0        1         2   

        PhysHlth  DiffWalk  Sex  Age  Education  Income  
0             20         0    0   11          4       5  
1              0         0    0   11          4       3  
2              0         0    0    9          4       7  
3             30         1    1   12          3       4  
4              0         1    1   13          5       6  
...          ...       ...  ...  ...        ...     ...  
236373         0         0    1   10          2       3  
236374         0         0    0    3          4       5  
236375         0         0    1    7          6      10  
236376         0         0    1   10          4       6  
236377         2         0    0    6          6       6  

[236378 rows x 24 columns]


## Made by-

<h3><a href="https://www.linkedin.com/in/prasun-maltare-94273a229/" target="_blank">Prasun Maltare</a></h3>




## Change Log <a id="20"></a>


|  Date             |   Change Description                   |
|--------------------|----------------------------------------|
| 20-03-2024        |Importing data | 
| 22-03-2024        |Cleaning and Modifying data              |
| 23-03-2024        |Further Cleaning and Saving in DataBase  |





<h3 align="center"> Thank you! <h3/><h5 align="center"> Check out the full project <a href="https://github.com/Prasun157/BRFSS-2021-Diabetes-Insight-A-Data-Science-Approach" target="_blank"> here<a/><h5/>
